### ISSUE TITLE
IndexOutOfBoundsException | Protocol message contained an invalid tag (zero)

### ISSUE THREAD

**Issue by lausdahl** [overturetool/overture-fmu#5]
```
DoStep skipping execution next time is: 1.5
DEBUG [Thread-0] (StateCache.java:75) - Collecting inputs from cache name: 'System.upperLevelSensor.upperlevel' value: '0.7457879109271885' size: '1' valueref: '3'
DEBUG [Thread-0] (StateCache.java:75) - Collecting inputs from cache name: 'System.lowerLevelSensor.lowerlevel' value: '0.004247648623389916' size: '1' valueref: '5'
DoStep called: 0.7480000000000006
DoStep skipping execution next time is: 1.5
com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
	at com.google.protobuf.InvalidProtocolBufferException.invalidTag(InvalidProtocolBufferException.java:89)
	at com.google.protobuf.CodedInputStream.readTag(CodedInputStream.java:158)
Internal error: Protocol message contained an invalid tag (zero).
	at com.lausdahl.examples.Service$Fmi2DoStepRequest.<init>(Service.java:6471)
	at com.lausdahl.examples.Service$Fmi2DoStepRequest.<init>(Service.java:6445)
	at com.lausdahl.examples.Service$Fmi2DoStepRequest$1.parsePartialFrom(Service.java:6840)
	at com.lausdahl.examples.Service$Fmi2DoStepRequest$1.parsePartialFrom(Service.java:6834)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:137)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:168)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:180)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:185)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at com.lausdahl.examples.Service$Fmi2DoStepRequest.parseFrom(Service.java:6586)
	at org.intocps.java.fmi.service.ProtocolDriver.run(ProtocolDriver.java:67)
	at java.lang.Thread.run(Thread.java:745)
com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
	at com.google.protobuf.InvalidProtocolBufferException.invalidTag(InvalidProtocolBufferException.java:89)
	at com.google.protobuf.CodedInputStream.readTag(CodedInputStream.java:158)
	at com.lausdahl.examples.Service$Fmi2DoStepRequest.<init>(Service.java:6471)
	at com.lausdahl.examples.Service$Fmi2DoStepRequest.<init>(Service.java:6445)
	at com.lausdahl.examples.Service$Fmi2DoStepRequest$1.parsePartialFrom(Service.java:6840)
	at com.lausdahl.examples.Service$Fmi2DoStepRequest$1.parsePartialFrom(Service.java:6834)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:137)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:168)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:180)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:185)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at com.lausdahl.examples.Service$Fmi2DoStepRequest.parseFrom(Service.java:6586)
	at org.intocps.java.fmi.service.ProtocolDriver.run(ProtocolDriver.java:67)
	at java.lang.Thread.run(Thread.java:745)
ERROR [Thread-0] (ProtocolDriver.java:146) - Decode error, returning FATAL message no matter what return type was expectede
com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
	at com.google.protobuf.InvalidProtocolBufferException.invalidTag(InvalidProtocolBufferException.java:89)
	at com.google.protobuf.CodedInputStream.readTag(CodedInputStream.java:158)
	at com.lausdahl.examples.Service$Fmi2DoStepRequest.<init>(Service.java:6471)
	at com.lausdahl.examples.Service$Fmi2DoStepRequest.<init>(Service.java:6445)
	at com.lausdahl.examples.Service$Fmi2DoStepRequest$1.parsePartialFrom(Service.java:6840)
	at com.lausdahl.examples.Service$Fmi2DoStepRequest$1.parsePartialFrom(Service.java:6834)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:137)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:168)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:180)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:185)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at com.lausdahl.examples.Service$Fmi2DoStepRequest.parseFrom(Service.java:6586)
	at org.intocps.java.fmi.service.ProtocolDriver.run(ProtocolDriver.java:67)
	at java.lang.Thread.run(Thread.java:745)
DEBUG [Thread-0] (StateCache.java:75) - Collecting inputs from cache name: 'System.upperLevelSensor.upperlevel' value: '0.7557879109271886' size: '1' valueref: '3'
DEBUG [Thread-0] (StateCache.java:75) - Collecting inputs from cache name: 'System.lowerLevelSensor.lowerlevel' value: '0.004247648623389916' size: '1' valueref: '5'

...
DoStep skipping execution next time is: 1.5
DEBUG [Thread-0] (StateCache.java:75) - Collecting inputs from cache name: 'System.upperLevelSensor.upperlevel' value: '0.9657879109271887' size: '1' valueref: '3'
DEBUG [Thread-0] (StateCache.java:75) - Collecting inputs from cache name: 'System.lowerLevelSensor.lowerlevel' value: '0.004247648623389916' size: '1' valueref: '5'
DoStep called: 0.9660000000000007
DoStep skipping execution next time is: 1.5
DEBUG [Thread-0] (StateCache.java:75) - Collecting inputs from cache name: 'System.upperLevelSensor.upperlevel' value: '0.9657879109271887' size: '1' valueref: '3'
DEBUG [Thread-0] (StateCache.java:75) - Collecting inputs from cache name: 'System.lowerLevelSensor.lowerlevel' value: '0.004247648623389916' size: '1' valueref: '5'
DoStep called: 0.9670000000000007
DoStep skipping execution next time is: 1.5
Exception in thread "Thread-0" java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.Collections$EmptyList.get(Collections.java:4454)
	at com.lausdahl.examples.Service$Fmi2SetRealRequest.getValues(Service.java:3992)
	at org.crescendo.fmi.CrescendoFmu.SetReal(CrescendoFmu.java:405)
	at org.intocps.java.fmi.service.ProtocolDriver.run(ProtocolDriver.java:106)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by lausdahl** [comment]
I'm closing this, it was an issue where two model using the same shared memory keys were simulated concurrently by two instances of the COE. We do not support this
